### ISSUE TITLE
can not get status of transaction 

### ISSUE THREAD

**Issue by lijianl** [TRON-US/tronweb#30]
`tronWeb.trx.getTransaction(tx).then(t => {
      console.log(JSON.stringify(t, null, 2));
    }).catch(err => console.error(err));

{
  "ret": [
    {}
  ],
  "signature": [
    "4cb0051824e370d1dbd251be0e0467910b8ca7495ac1e472ecfe317fd238c2a6604b44a27ab2c8d957e4453d36fbcddf01203fb84ad38be80629ea326043219701"
  ],
  "txID": "2500376771711f9d142941ab1c6dcb70c2bfba8bc9225ce63e650e54cae53df8",
}

there is not status return

**Comment by lijianl** [comment]
ret is empty .... 
could any body help me with this ??

**Comment by UnforgivenZZZ** [comment]
> ret is empty ....
> could any body help me with this ??

it is not an issue with tronweb, it is some SR doesn't have the proper set up for their witness nodes that produces blocks
