### ISSUE TITLE
Smart Contract delpoyement fails "Invalid issuer address provided"

### ISSUE THREAD

**Issue by amovah** [TRON-US/tronweb#32]
I don't it's tronweb issue or tronlink. but when I'm going to deploy contract through tronlink it gives me this error: `Invalid issuer address provided`. but when I'm using tronweb from myserver. everything works fine.

**Comment by sullof** [comment]
There can be a difference because TronLink does not use the latest version of TronWeb. In any case, it is a TronLink issue. Can you please open an issue there?
