### ISSUE TITLE
How to calculate the bytes size of a transaction?

### ISSUE THREAD

**Issue by StillFantastic** [TRON-US/tronweb#46]
I want to calculate the net usage before broadcasting the transaction, can I do that with tronweb? 
I have found that there is a `getRowBytesFromTransactionBase64` function in `src/utils/crypto.js`, is it the solution? If so, how can I convert a transaction into base64 format?
Thanks a lot!

**Comment by JessDotJS** [comment]
Hello, could you please provide an example of how this can be achieved with TronWeb/TronStationSDK?
