### ISSUE TITLE
how to get contract return value and transaction hash at the same time ?

### ISSUE THREAD

**Issue by rahuldamodar94** [TRON-US/tronweb#52]
async function triggercontract2() {
    let contractInstance = await tronWeb.contract().at('TVPGpHt8GvpMSqpdhjKcXq6ehtEACiUq8Z');

    let args = {
        callValue: 0,
        shouldPollResponse: true
    }
    let result = await contractInstance.create('2', '30', '3', '3433', 'abcd', 'efg', '0.2334', '0.5', '0.1', '10', '56', 'TEwbscPMyadgq5oAK7NsdPQTXBSUtLnnwf', 'TEwbscPMyadgq5oAK7NsdPQTXBSUtLnnwf', 'SELL').send(args);

    return result;
}

In the above code, i am trying to store some details in the smart contract i have deployed on the tron network. According to the solidity code, when I store something in the contract , a unique hash is returned. When i keep shouldPollResponse as true in the args, I get the unique hash as response. When i keep shouldPollResponse as false, I get the tron transaction hash as response. But I wish to know if there is any way to get both together. I  need to save the unique hash to later fetch the records from the smart contract. And I need the tron transaction hash to maintain a proof that the details have been stored in tron blockchain. This tx hash can be used in tron scan to verify if the transaction has actually happened.

Thank you in advance.

**Comment by sullof** [comment]
It should be not difficult to add an option for that. Let me think about it. 
I will comment later if I find a solution for that. Thanks.

**Comment by sullof** [comment]
@rahuldamodar94, please, look at the PR #64 and tell me if that looks like a good solution for you. Thanks.

**Comment by sullof** [comment]
If you like it, would you live a thumbs up there and close this issue, please?

**Comment by sullof** [comment]
I think that the PR works well. I merged it. 
Thanks for the request/suggestion!
