### ISSUE TITLE
Failed to initialise TronWeb

### ISSUE THREAD

**Issue by blockinator** [TRON-US/tronweb#58]
Hi I get the following error when trying to interact with a webpage with TronLink:

`[ERROR]: Failed to initialise TronWeb TypeError: Cannot read property 'filter' of undefined 
at pageHook.js:44451
`

This is the line at `pageHook.js:44451`:

`var c = phishingList.filter(function (_ref2) {`

`

**Comment by sullof** [comment]
I think this is a TronLink issue. Open the issue at 
https://github.com/TronLink/tronlink-extension/issues
