### ISSUE TITLE
Public Key to Address Conversion confusion

### ISSUE THREAD

**Issue by viswanathkgp12** [TRON-US/tronweb#62]
Public Key to Address Conversion for Testnet Output is different when done through:
1. TronWeb
2. https://shasta.tronscan.org/#/tools/tron-convert-tool

This is because ADDRESS_PREFIX is hardcoded [here](https://github.com/TRON-US/tronweb/blob/master/src/utils/address.js). 

But as per the Shasta tool, it should be: `0x41` for Mainnet and `0xa0` from Testnet

Please clear the confusion on which format is actually valid.

For reference, here is what I have been doing:
`
const pubBytes = hexStr2byteArray(ecPoint);
const addressBytes = TronWeb.utils.crypto.computeAddress(pubBytes);
const base58Address = TronWeb.utils.crypto.getBase58CheckAddress(addressBytes);
`

**Comment by sullof** [comment]
What are you talking about? I don't understand.
The command to convert addresses in TronWeb are `tronWeb.address.fromHex` and `tronWeb.address.toHex`.
In any case, a Tron address in hexadecimal format starts with `41`. Inside API results, though, for compatibility reason, it appears in Ethereum format, starting from `0x`.
Could you please add details?

**Comment by sullof** [comment]
Anyway, that is a design issue that cannot be fixed by TronWeb, because the TVM works that way. I am going to close the issue.
