### ISSUE TITLE
I cant get TRC20 transactions to an address

### ISSUE THREAD

**Issue by tummybos** [TRON-US/tronweb#63]
I am using tron web to query transactions of an address but it does not return transactions sent to that address where token transferred is TRC20.

This does not work. I want to get the transactions on an address and get both TRX, trc10 and trc20 transactions.

What am I doing wrong or how to do that?

Here is my code block:

  tronWeb.setDefaultBlock("latest");
  var result = await tronGrid.account.getTransactions(address, {
    only_confirmed: true,
    only_to: true,
    limit: 10
  });
  console.log(JSON.stringify(result));
})();

**Comment by sullof** [comment]
This is not a bug.
`getTransaction` gets you data about a transaction. What you are looking for is a transfer of TRC20 token, which is something you have looking at the `Transfer` events emitted by the contract.
TronGrid is adding a new API just for that. It will be ready very soon.
