### ISSUE TITLE
"Failed to execute" error when calling contract method

### ISSUE THREAD

**Issue by kevholder** [TRON-US/tronweb#78]
I am trying to implement a Proxy contract that uses delegatecall to proxy method calls to a proxied contract. When I attempt to call one of the proxied method `await proxyContract.synthetixProxy().call();`, tronweb returns "Failed to execute" and its transaction object looks like:

```javascript
{ visible: false,
  txID:
   'ca5bc1666d60656d245379fe54336a2e17950963d5c5f5a0b4cc6627650d2e51',
  raw_data:
   { contract: [ [Object] ],
     ref_block_bytes: '3f09',
     ref_block_hash: '3ac9c15edcb67855',
     expiration: 1583557074000,
     fee_limit: 1000000000,
     timestamp: 1583557016105 },
  raw_data_hex:
   '0a023f0922083ac9c15edcb6785540d0b8ed9a8b2e5a6d081f12690a31747970652e676f6f676c65617069732e636f6d2f70726f746f636f6c2e54726967676572536d617274436f6e747261637412340a1541a8a07f09def5e6a4462df90068c11abf6224e865121541337f3081a1fd68f222ccc0c398691ccf811e734b2204bdd1248270a9f4e99a8b2e90018094ebdc03' }
```

I am not sure how to further debug this issue. From what I understand, the problem is that the transaction does not contain a `constant_result` property. Why not? How can I debug this issue... I'm lost.

I could provide full code to reproduce if it helps.

**Comment by kevholder** [comment]
I think I figure the issue.

**Comment by Lefgk** [comment]
could you give the solution pls ?

**Comment by noda-sin** [comment]
If the ABI isn't published, we should use `triggerConstantContract` instead of `triggerSmartContract`. right?
https://github.com/tronprotocol/tips/issues/31
https://stackoverflow.com/questions/64121820/how-to-call-balanceof-method-for-non-published-abi

**Comment by chendatony31** [comment]
Just add  a `{ _isConstant: true }` using `call()` 
`await proxyContract.synthetixProxy().call({ _isConstant: true });`
